### PR TITLE
fix: pynvml returns str since 11.5.0

### PR DESCRIPTION
**Pull request by hredestig**
fix by checking type return value instead of implicitly via six.PY3

### CODE REVIEW

**Comment by kenny-ezirim** [comment]
When is the planned release for this fix?

**Comment by jessythomas** [comment]
I am also interested in the timeline for the fix.

**Comment by hredestig** [comment]
> @hredestig When is the planned release for this fix?

Not up to me but the maintainer.. as far as I'm concerned it's ready and can be merged.

**Comment by bzamecnik** [comment]
@hredestig Thank you for the fix. Sorry for a delay, I was on vacation.

**Pull request merged**
